import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import { GoogleOAuthProvider } from "@react-oauth/google";

const montserrat = Montserrat({
  weight: ["900", "700"],
  subsets: ["latin"],
  variable: '--font-montserrat'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const clientId = process.env.CLIENTID
  return (
    <html lang="en">
       <GoogleOAuthProvider clientId={`${clientId}`}>
      <body className={montserrat.className}>{children}</body>
      </GoogleOAuthProvider>
    </html>
  )
}
